Acessos do administrador na plataforma
agleicesousa/civitas-api pull request #19
Opened 2024-10-23 00:10 UTC by agleicesousa

**Melhorias e Refinamentos Implementados:**

**CRUD** - Implementado o gerenciamento completo de usuários administradores no banco de dados.
**JWT** - Adicionada verificação de privilégios de administrador através do token JWT gerado durante o login.
**TSDoc** - Melhorada a documentação do código com TSDoc, removendo informações desnecessárias e esclarecendo melhor cada parte do código.

2024-10-24 17:38 UTC, luiz-jarduli requested changes

2024-10-24 17:38 UTC, luiz-jarduli commented on .env.exemple
O nome do arquivo está `exemple`

2024-10-24 17:38 UTC, luiz-jarduli commented on .env.exemple
> +DB_HOST = 172.20.0.3
nos exemplos de env, temos q tomar cuidado para não subir dados sensíveis, o ideal é só ter a estrutura de chaves mesmo, e nem precisamos ficar atualizando também, só se a chave mudar

2024-10-24 17:38 UTC, luiz-jarduli commented on src/controller/adminController.ts
> +  private validarEmail(email: string): boolean {
Essa validação de email está duplicada aqui e no arquivo do adminService. 

Sugestão: Acho que vcs poderiam utilizar o express-validators no projeto, o que acham? Ele possuim diversas funções que podem ajudar principalmente nessa parte de validação do payload.

Segue a documentação: https://express-validator.github.io/docs

Segue a doc falando sobre as validações, inclusive o isEmail, que valida facilmente campos de email: /guides/validation-chain/#standard-validatorssanitizers

2024-10-24 20:31 UTC, agleicesousa commented on .env.exemple
é pra ser um arquivo de exemplo de uma .env, não? eu só conheço o .env.exemple que faz isso...

2024-10-28 17:02 UTC, luiz-jarduli approved these changes

2024-10-28 17:02 UTC, luiz-jarduli commented on .env.exemple
É o nome mesmo que está incorreto, ao invés de example, está exemple

2024-10-28 19:00 UTC, merged