Refactor/membros
agleicesousa/civitas-api pull request #8
Opened 2024-10-16 17:22 UTC by agleicesousa

Adicionei o arquivo **baseEntity.ts** para centralizar parâmetros comuns que serão reutilizados pelos outros módulos, evitando a repetição de código.

2024-10-16 17:57 UTC, luiz-jarduli commented on src/entities/adminEntities.ts
> +  @BeforeInsert()
Acho que a senha deveria ser uma coluna também né, será que faltou ajustar algo?

2024-10-16 17:58 UTC, luiz-jarduli requested changes

2024-10-16 17:58 UTC, luiz-jarduli commented on src/entities/adminEntities.ts
> +  @BeforeInsert()
Acho que a senha deveria ser uma coluna também né, será que faltou ajustar algo?

2024-10-16 18:16 UTC, agleicesousa commented on src/entities/adminEntities.ts
> +  @BeforeInsert()
feito!

2024-10-16 20:09 UTC, luiz-jarduli requested changes

2024-10-16 20:09 UTC, luiz-jarduli commented on src/utils/senhaUtils.ts
> +export async function criptografarSenha(senhaPlana: string): Promise<string> {
Documente utilizando padrão TSDoc as funções e métodos, ai acho que mantemos mais legível

2024-10-16 20:09 UTC, luiz-jarduli commented on src/utils/senhaUtils.ts
> +export function CriptografarSenhaAntesDeInserir(): MethodDecorator {
Gostei da solução de criptografia, mas será que precisaria de um decorator? Normalmente abstraímos quando temos intenção de reutilizar em algum lugar. Se tiver alguma ideia de onde possa ser reutilizado, pode desconsiderar o questionamento tudo bem?

2024-10-17 19:54 UTC, luiz-jarduli approved these changes

2024-10-17 19:54 UTC, merged